name: Code Coverage Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ^16.14.0

    - name: Set up environment variables
      run: echo "${{ secrets.DOTENVFILE }}" > .env

    - name: Install dependencies
      run: 'yarn install'

    - name: Fix node_modules
      run: chmod +x ./fix_node_modules.sh
    - name: Run the fix_node_modules script
      run: ./fix_node_modules.sh

    - name: Run tests and generate coverage reports
      run: 'yarn nx run-many --target=test --all --parallel --skip-nx-cache --coverage --testTimeout=10000'

    - name: Run api-e2e tests and generate coverage reports
      run: 'yarn nx run api-e2e:e2e --all --parallel --skip-nx-cache --coverage --testTimeout=10000 --detectOpenHandles=true'

    # Uncomment this once the app-e2e tests are working/up to date
    # - name: Run app-e2e tests and generate coverage reports
    #   run: 'yarn nx run app-e2e:e2e --all --parallel --skip-nx-cache --coverage --testTimeout=10000 --detectOpenHandles=true'

    - name: Upload coverage reports to Codecov
      # uses: codecov/codecov-action@v3 
      # env:
      #   CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        # Replace `linux` below with the appropriate OS
        # Options are `alpine`, `linux`, `macos`, `windows`
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${{ secrets.CODECOV_TOKEN }} -f coverage-final.json
