name: Build, Lint and Test
'on':
  pull_request:
    branches:
      - '*_test'
      - main
  push:
    branches:
      - '*_test'
      - main
      - dev
jobs:
  all_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.DOTENVFILE }}" > .env
      - run: 'yarn install'
      - run: 'chmod +x ./fix_node_modules.sh'
      - run: './fix_node_modules.sh'
      - run: 'yarn nx run-many --target=lint --all --parallel --skip-nx-cache'
      - run: 'yarn nx run-many --target=build --all --parallel --skip-nx-cache'
      - run: 'yarn nx run-many --target=test --all --parallel --skip-nx-cache --coverage --testTimeout=10000'
      # - run: 'yarn nx run app-e2e:e2e --all --parallel --skip-nx-cache --coverage --testTimeout=10000 --detectOpenHandles=true'
      - run: 'yarn test:integration --coverage'
      - name: Upload coverage reports to Codecov 
        # uses: codecov/codecov-action@v3 
        # env:
        #   CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          # Replace `linux` below with the appropriate OS
          # Options are `alpine`, `linux`, `macos`, `windows`
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${{ secrets.CODECOV_TOKEN }} -f coverage-final.json
