name: Build, Lint and Test
'on':
  pull_request:
    branches:
      - '*_test'
  push:
    branches:
      - '*_test'
jobs:
  all_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.DOTENVFILE }}" > .env
      - run: 'yarn install'
      - run: 'chmod +x ./fix_node_modules.sh'
      - run: './fix_node_modules.sh'
      - run: 'yarn nx run-many --target=lint --all --parallel --skip-nx-cache'
      - run: 'yarn nx run-many --target=build --all --parallel --skip-nx-cache'
      - run: 'yarn nx run-many --target=test --all --parallel --skip-nx-cache --coverage --testTimeout=10000'
      - run: 'yarn nx run app-e2e:e2e --all --parallel --skip-nx-cache --coverage --testTimeout=10000 --detectOpenHandles=true'
      - run: 'yarn test:integration'
